name: 🔑 Test SSH Connection

on: [workflow_dispatch]

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: 🔑 Tester la connexion SSH avec Ubuntu
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: benyprof
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Connexion SSH réussie !"
